// This file is automatically generated. Do not modify it manually.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: 'AIzaSyCyBU_CqZTP96FNmz3AsCnBq1sq61x7GXE',
  authDomain: 'studio-946320409-15678.firebaseapp.com',
  projectId: 'studio-946320409-15678',
  storageBucket: 'studio-946320409-15678.firebasestorage.app',
  messagingSenderId: '75900551142',
  appId: '1:75900551142:web:d6f0ae934cfe2abf69e027',
};
