// This file is automatically generated. Do not modify it manually.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "AIzaSyAyIrC1zZx716NGAQxrqRyY_inbNA2XD-M",
  authDomain: "studio-1297545116-fb1b2.firebaseapp.com",
  projectId: "studio-1297545116-fb1b2",
  storageBucket: "studio-1297545116-fb1b2.appspot.com",
  messagingSenderId: "448796633714",
  appId: "1:448796633714:web:cfc521239077757d1f30eb",
};
